import { ArrowRight, BookOpen, ExternalLink, Search as SearchIcon } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import CatalogShell from "@/components/CatalogShell";
import { LogoMark, ProjectCard, SourceLink, StagePill } from "@/components/CatalogUI";
import { ecosystem, founder, projects, researchItems } from "@/data/catalog";

export function ProjectsPage() { const [filter,setFilter]=useState("All"); const categories=["All",...Array.from(new Set(projects.map(p=>p.category)))]; const items=filter === "All" ? projects : projects.filter(p=>p.category===filter); return <CatalogShell title="Projects in motion." intro="A living collection of research initiatives, proposed architectures, planned demonstrations, and future directions. Every project carries its own identity, stage, and public source boundary."><div className="catalog-filter-row">{categories.map(c=><button className={filter===c?"active":""} key={c} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="catalog-project-grid">{items.map(p=><ProjectCard key={p.slug} project={p}/>)}</div></CatalogShell>; }
export function ProjectDetailPage() { const [,params]=useRoute("/projects/:slug"); const project=projects.find(p=>p.slug===params?.slug); if(!project) return <NotFoundPage />; return <CatalogShell title={project.name} intro={project.description}><div className="project-detail"><div className="project-detail-visual" style={{backgroundImage:`linear-gradient(145deg,rgba(2,20,14,.05),rgba(2,20,14,.78)),url(${project.image})`}}><LogoMark item={project} detail /></div><div className="project-detail-copy"><div className="detail-brand"><LogoMark item={project} detail /><div><span className="section-kicker">{project.eyebrow}</span><h2>{project.name}</h2></div></div><div className="detail-meta"><StagePill stage={project.stage} kind={project.stageKind}/><span>{project.category}</span>{project.tags.map(t=><span key={t}>{t}</span>)}</div><p className="detail-status">{project.statusNote}</p><h3>Research focus</h3><ul>{project.focus.map(item=><li key={item}>{item}</li>)}</ul><SourceLink href={project.sourceUrl} label={`Read ${project.sourceLabel}`} /><Link className="detail-back" href="/projects">Back to all projects <ArrowRight size={15}/></Link></div></div></CatalogShell>; }
export function ResearchPage() { return <CatalogShell title="Research, with provenance." intro="Research is presented as a living index: each entry links back to the project it extends and makes its maturity visible."><div className="research-grid">{researchItems.map(item=><article className="research-index-card" key={item.title}><img src={item.image} alt=""/><div><div className="catalog-card-top"><span>{item.category}</span><StagePill stage={item.stage} kind={item.stageKind}/></div><h2>{item.title}</h2><p>{item.summary}</p><Link href={`/projects/${item.projectSlug}`}>Open related project <ArrowRight size={15}/></Link></div></article>)}</div></CatalogShell>; }
export function LibraryPage() { const resources=[['Public Research Registry','Project stages, current public disclosures, and the boundary between research plans and validated results.', 'https://github.com/Daemon22/Gqobonco/blob/main/docs/research-registry.md'],['Gqobonco Project Overview','The public README: purpose, key initiative, ecosystem context, and ways to contribute.','https://github.com/Daemon22/Gqobonco/blob/main/README.md'],['Gqobonco Source Repository','Browse the public website source, documentation, and issue tracker.','https://github.com/Daemon22/Gqobonco'],['Contribute to Gqobonco','Open the contribution path for research, documentation, and website improvements.','https://github.com/Daemon22/Gqobonco/issues/new']]; return <CatalogShell title="Knowledge library." intro="A grounded public reading room for documents, registry entries, and source material connected to Gqobonco’s work."><div className="library-list">{resources.map(([title,desc,href])=><a className="library-row" href={href} target="_blank" rel="noreferrer" key={title}><span className="library-icon"><BookOpen size={20}/></span><span><b>{title}</b><small>{desc}</small></span><ExternalLink size={16}/></a>)}</div></CatalogShell>; }
export function EcosystemPage() { return <CatalogShell title="The wider living system." intro="Gqobonco’s catalog is distinct from its ecosystem relationships. These companion projects are linked where their roles are documented publicly."><div className="ecosystem-grid">{ecosystem.map(item=><a className="ecosystem-card" href={item.href} target="_blank" rel="noreferrer" key={item.name}><LogoMark item={item}/><span className="section-kicker">{item.role}</span><h2>{item.name}</h2><p>{item.description}</p><ExternalLink size={16}/></a>)}</div></CatalogShell>; }
export function AboutPage() { return <CatalogShell title="About GOBONCO." intro="The River of Lineage. Nourishing the Collective Mind."><div className="about-grid"><div><span className="section-kicker">{founder.canonicalLine}</span><h2>Knowledge flows in every direction.</h2><p>{founder.statement}</p><p>{founder.mediumBio}</p><p><em>“We are the generation that remembers.”</em></p></div><div className="about-principles"><div><b>Nature</b><span>Land, water, culture, knowledge, and primary production are the roots.</span></div><div><b>People</b><span>Capability returns to the communities and systems that sustain it.</span></div><div><b>Technology</b><span>Build what must exist, with the hand remaining responsible for the blade.</span></div><div><b>Founder</b><span>{founder.name} · {founder.location} · Electrical Engineering student.</span></div></div></div></CatalogShell>; }
export function CommunityPage() { return <CatalogShell title="Join the river." intro="Gqobonco grows through research, documentation, thoughtful critique, and contributions that help African knowledge reclaim authorship of its digital future."><div className="community-panel"><h2>Bring a project, research note, or question.</h2><p>Start with the public repository, browse the research registry, or open an issue to contribute to the collection.</p><div><a className="catalog-cta" href="https://github.com/Daemon22/Gqobonco/issues/new" target="_blank" rel="noreferrer">Open a contribution <ArrowRight size={15}/></a><Link className="catalog-cta secondary" href="/library">Read the library <ArrowRight size={15}/></Link></div></div></CatalogShell>; }
export function SearchPage() { const [query,setQuery]=useState(""); const [location]=useLocation(); const results=useMemo(()=>{const q=query.toLowerCase(); return projects.filter(p=>`${p.name} ${p.category} ${p.description} ${p.tags.join(" ")}`.toLowerCase().includes(q));},[query]); return <CatalogShell title="Search the collection." intro="Find projects and research by name, sector, stage, or theme."><div className="catalog-search"><SearchIcon size={19}/><input autoFocus placeholder="Search projects, research, knowledge…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{query && <div className="search-results">{results.map(p=><Link href={`/projects/${p.slug}`} key={p.slug}><LogoMark item={p}/><span><b>{p.name}</b><small>{p.category} · {p.stage}</small></span><ArrowRight size={15}/></Link>)}{!results.length&&<p>No matching work yet.</p>}</div>}{!query&&<p className="search-hint">Try “water”, “language”, “industry”, or “future”.</p>}</CatalogShell>; }
export function NotFoundPage() { return <CatalogShell title="The current does not flow here." intro="This page is not part of the public river yet."><Link className="catalog-cta" href="/projects">Return to projects <ArrowRight size={15}/></Link></CatalogShell>; }
